# Generated by Django 5.0 on 2024-11-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(help_text='RUN del empleado', max_length=12, unique=True)),
                ('nombres', models.CharField(help_text='Nombres del empleado', max_length=100)),
                ('apellidos', models.CharField(help_text='Apellidos del empleado', max_length=100)),
                ('email', models.EmailField(help_text='Correo electrónico del empleado', max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, help_text='Teléfono del empleado', max_length=15)),
                ('cargo', models.CharField(help_text='Cargo del empleado', max_length=100)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
    ]
