# Generated by Django 5.0.6 on 2024-11-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre del servicio', max_length=200)),
                ('descripcion', models.TextField(help_text='Descripción del servicio')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio del servicio', max_digits=10)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
    ]
