# Generated by Django 5.0.6 on 2024-11-18 20:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0004_proveedor_alter_servicio_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_pedido', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='coreapp.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='coreapp.proveedor')),
            ],
        ),
    ]
