# Generated by Django 5.0.6 on 2024-11-12 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0005_usuarios_is_active_usuarios_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='last_login',
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='run',
            field=models.CharField(max_length=12),
        ),
    ]
