# Generated by Django 5.0.6 on 2024-11-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0007_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12)),
                ('direccion', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('descripcion_servicios', models.TextField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('impresa', models.BooleanField(default=False)),
            ],
        ),
    ]
